# Generated by Django 2.2 on 2019-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
